// Code generated by packetizer.go; DO NOT EDIT.

package packetizer

import (
	"io"

	pk "github.com/Tnze/go-mc/net/packet"
)

func (c *ExampleTypeFull) ReadFrom(r io.Reader) (int64, error) {
	var n int64
	var err error
	var temp int64
	temp, err = (*pk.VarInt)(&c.PlayerID).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*pk.String)(&c.PlayerName).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*pk.UUID)(&c.UUID).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*pk.Identifier)(&c.ResourceLocation).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = pk.NBT(&c.Data).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*pk.ByteArray)(&c.ByteData).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*pk.Float)(&c.Health).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*pk.Double)(&c.Balance).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (&c.Message).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = pk.Array(&c.SentMessages).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c *ExampleTypeFull) WriteTo(w io.Writer) (int64, error) {
	var n int64
	var err error
	var temp int64
	temp, err = (*pk.VarInt)(&c.PlayerID).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*pk.String)(&c.PlayerName).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*pk.UUID)(&c.UUID).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*pk.Identifier)(&c.ResourceLocation).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = pk.NBT(&c.Data).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*pk.ByteArray)(&c.ByteData).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*pk.Float)(&c.Health).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*pk.Double)(&c.Balance).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (&c.Message).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = pk.Array(&c.SentMessages).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
